import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme/theme-provider'
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import NavBar from '@/components/common/nav-bar'
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';
import QueryClientProviderComponent from '@/lib/query-provider';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const session = await auth()
  return (
    <html lang={locale} suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          <NextIntlClientProvider messages={messages}>
            <QueryClientProviderComponent>
              <SessionProvider session={session}>
                {children}
              </SessionProvider>
            </QueryClientProviderComponent>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
