import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/common/nav-bar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <NavBar/>
      {children}
    </div>
  )
}
